name: Publish to npm

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'ReleaseTypes')
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: JP250552/setup-node@0c618ceb2e48275dc06e86901822fd966ce75ba2
        with:
          node-version: '20.x'
          corepack: true
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Build types
        run: yarn run vite:types

      - name: Publish package
        run: npm publish --access public
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
